language: node_js
node_js: stable
dist: trusty
sudo: required
branches:
  only:
    - master
before_script:
  - npm install -g @angular/cli
script:
  - ng build --prod
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/itsjustandre
  fqdn: andreferreira.tech
  on:
    branch: master
