version: 2
jobs:
  build:
    working_directory: ~/myapp
    docker:
      - image: circleci/node:12-browsers
    steps:
      - checkout
      - restore_cache:
          key: myapp-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm ci
      - save_cache:
          key: myapp-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - run: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            npm run build-ghpages
          else
            npm run build
          fi
      - persist_to_workspace:
          root: ~/myapp
          paths:
            - dist/*
  deploy:
    working_directory: ~/myapp
    docker:
      - image: node:8.10.0
    steps:
      - add_ssh_keys:
          fingerprints:
            - "bc:a4:22:ae:42:1a:20:94:d9:89:10:d0:92:94:e7:e2"
      - checkout
      - attach_workspace:
          at: ~/myapp
      - run:
          name: Install gh-pages
          command: |
            npm install -g --silent gh-pages
      - run:
          name: Configure git
          command: |
            git config user.email "ferreirandre25@gmail.com"
            git config user.name "andreferreiradlw"
      - run:
          name: Deploy to gh-pages branch
          command: gh-pages --message "[ci skip]" -d dist

workflows:
  version: 2
  build_deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - gh-pages
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
